"""
handshake.py — Mutual challenge–response authentication with digital signatures.

Handshake sequence
==================

  Client                                   Server
    │                                        │
    │── ClientHello ────────────────────────>│
    │   (nonce_c, timestamp_c)               │  verify timestamp freshness
    │                                        │
    │<───────────────────── ServerHello ─────│
    │   (nonce_s, timestamp_s,               │
    │    challenge_s = HMAC(nonce_c‖nonce_s), │
    │    sig_s = Sign(nonce_c‖nonce_s, sk_s))│
    │                                        │
    │  verify sig_s with pk_s                │
    │── ClientResponse ────────────────────>│
    │   (challenge_response =                │
    │      HMAC(nonce_s‖nonce_c),            │
    │    sig_c = Sign(nonce_s‖nonce_c, sk_c))│
    │                                        │  verify sig_c with pk_c
    │<───────────────── ServerDone ──────────│
    │   (encrypted_session_key)              │
    │                                        │
    ╰────── session established ─────────────╯

Session key is generated by the server, encrypted with the client's RSA
public key, and sent in ServerDone.

Non-repudiation: both sides produce RSA-PSS signatures over the handshake
nonces, proving identity to a third-party auditor.

Anti-replay: nonces are random 16-byte values; timestamps must be within
``MAX_TIMESTAMP_DRIFT`` seconds of the receiver's clock.
"""

import json
import logging
import os
import struct
import time
import socket

from cryptography.hazmat.primitives.asymmetric import rsa, padding as asym_padding
from cryptography.hazmat.primitives import hashes, serialization

from crypto.protocol import (
    MessageType,
    send_frame,
    recv_frame,
    SESSION_ID_SIZE,
)
from crypto.crypto_utils import (
    generate_session_key,
    compute_hmac,
    verify_hmac,
    derive_keys,
    HMAC_KEY_SIZE,
)
from auth.signatures import sign_data, verify_signature

logger = logging.getLogger("vpn.handshake")

# ---------------------------------------------------------------------------
# Tunables
# ---------------------------------------------------------------------------
MAX_TIMESTAMP_DRIFT = 300          # seconds — 5 min tolerance for clock skew
HANDSHAKE_TIMEOUT = 30             # seconds — max time for full handshake
CHALLENGE_HMAC_KEY = b"challenge"  # fixed key for challenge HMAC (not secret)

# Null session-id used during handshake (real one comes in ServerDone)
_NULL_SID = b"\x00" * SESSION_ID_SIZE


# ---------------------------------------------------------------------------
# Serialization helpers  (JSON payloads for handshake messages)
# ---------------------------------------------------------------------------
def _encode_hs(obj: dict) -> bytes:
    return json.dumps(obj).encode("utf-8")


def _decode_hs(data: bytes) -> dict:
    return json.loads(data.decode("utf-8"))


# ---------------------------------------------------------------------------
# Client-side handshake
# ---------------------------------------------------------------------------
def client_handshake(
    sock: socket.socket,
    client_private_key: rsa.RSAPrivateKey,
    server_public_key: rsa.RSAPublicKey,
) -> tuple[bytes, bytes, bytes]:
    """Run the client side of the mutual-auth handshake.

    Returns:
        (session_id, enc_key, mac_key)

    Raises on any authentication failure.
    """
    sock.settimeout(HANDSHAKE_TIMEOUT)

    # ── 1. ClientHello ──────────────────────────────────────────────────
    nonce_c = os.urandom(16)
    ts_c = time.time()
    hello_payload = _encode_hs({
        "nonce_c": nonce_c.hex(),
        "timestamp": ts_c,
    })
    send_frame(sock, MessageType.HANDSHAKE_CLIENT_HELLO, _NULL_SID, hello_payload)
    logger.info("TX ClientHello  nonce=%s", nonce_c.hex()[:12])

    # ── 2. Receive ServerHello ──────────────────────────────────────────
    msg_type, _, sh_payload = recv_frame(sock)
    if msg_type != MessageType.HANDSHAKE_SERVER_HELLO:
        raise ValueError(f"Expected ServerHello, got {msg_type.name}")

    sh = _decode_hs(sh_payload)
    nonce_s = bytes.fromhex(sh["nonce_s"])
    ts_s = sh["timestamp"]
    challenge_s = bytes.fromhex(sh["challenge"])
    sig_s = bytes.fromhex(sh["signature"])

    # verify timestamp freshness
    if abs(time.time() - ts_s) > MAX_TIMESTAMP_DRIFT:
        raise ValueError("ServerHello timestamp outside acceptable window")

    # verify server signature  (non-repudiation)
    transcript = nonce_c + nonce_s
    if not verify_signature(transcript, sig_s, server_public_key):
        raise ValueError("Server signature verification FAILED — aborting")
    logger.info("Server signature verified ✓")

    # verify challenge
    expected_challenge = compute_hmac(nonce_c + nonce_s, CHALLENGE_HMAC_KEY)
    if not verify_hmac(nonce_c + nonce_s, challenge_s, CHALLENGE_HMAC_KEY):
        raise ValueError("Server challenge HMAC mismatch")

    # ── 3. ClientResponse ───────────────────────────────────────────────
    challenge_response = compute_hmac(nonce_s + nonce_c, CHALLENGE_HMAC_KEY)
    transcript_cr = nonce_s + nonce_c
    sig_c = sign_data(transcript_cr, client_private_key)

    cr_payload = _encode_hs({
        "challenge_response": challenge_response.hex(),
        "signature": sig_c.hex(),
    })
    send_frame(sock, MessageType.HANDSHAKE_CLIENT_RESPONSE, _NULL_SID, cr_payload)
    logger.info("TX ClientResponse")

    # ── 4. Receive ServerDone ───────────────────────────────────────────
    msg_type, _, sd_payload = recv_frame(sock)
    if msg_type != MessageType.HANDSHAKE_SERVER_DONE:
        if msg_type == MessageType.ERROR:
            raise ValueError(f"Server rejected handshake: {sd_payload.decode()}")
        raise ValueError(f"Expected ServerDone, got {msg_type.name}")

    sd = _decode_hs(sd_payload)
    session_id = bytes.fromhex(sd["session_id"])
    encrypted_session_key = bytes.fromhex(sd["encrypted_session_key"])

    # Decrypt session key with our private key
    session_key = client_private_key.decrypt(
        encrypted_session_key,
        asym_padding.OAEP(
            mgf=asym_padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
        ),
    )

    enc_key, mac_key = derive_keys(session_key, salt=session_id)
    logger.info("Handshake complete — session %s", session_id.hex()[:12])
    return session_id, enc_key, mac_key


# ---------------------------------------------------------------------------
# Server-side handshake
# ---------------------------------------------------------------------------
def server_handshake(
    sock: socket.socket,
    server_private_key: rsa.RSAPrivateKey,
    client_public_key: rsa.RSAPublicKey,
) -> tuple[bytes, bytes, bytes]:
    """Run the server side of the mutual-auth handshake.

    Returns:
        (session_id, enc_key, mac_key)

    Raises on any authentication failure.
    """
    sock.settimeout(HANDSHAKE_TIMEOUT)

    # ── 1. Receive ClientHello ──────────────────────────────────────────
    msg_type, _, ch_payload = recv_frame(sock)
    if msg_type != MessageType.HANDSHAKE_CLIENT_HELLO:
        raise ValueError(f"Expected ClientHello, got {msg_type.name}")

    ch = _decode_hs(ch_payload)
    nonce_c = bytes.fromhex(ch["nonce_c"])
    ts_c = ch["timestamp"]

    # verify timestamp freshness
    if abs(time.time() - ts_c) > MAX_TIMESTAMP_DRIFT:
        _send_error(sock, "ClientHello timestamp outside acceptable window")
        raise ValueError("ClientHello timestamp rejected")

    logger.info("RX ClientHello  nonce=%s", nonce_c.hex()[:12])

    # ── 2. ServerHello ──────────────────────────────────────────────────
    nonce_s = os.urandom(16)
    ts_s = time.time()
    transcript = nonce_c + nonce_s
    challenge_s = compute_hmac(transcript, CHALLENGE_HMAC_KEY)
    sig_s = sign_data(transcript, server_private_key)

    sh_payload = _encode_hs({
        "nonce_s": nonce_s.hex(),
        "timestamp": ts_s,
        "challenge": challenge_s.hex(),
        "signature": sig_s.hex(),
    })
    send_frame(sock, MessageType.HANDSHAKE_SERVER_HELLO, _NULL_SID, sh_payload)
    logger.info("TX ServerHello")

    # ── 3. Receive ClientResponse ───────────────────────────────────────
    msg_type, _, cr_payload = recv_frame(sock)
    if msg_type != MessageType.HANDSHAKE_CLIENT_RESPONSE:
        raise ValueError(f"Expected ClientResponse, got {msg_type.name}")

    cr = _decode_hs(cr_payload)
    challenge_response = bytes.fromhex(cr["challenge_response"])
    sig_c = bytes.fromhex(cr["signature"])

    # verify challenge response
    expected_cr = compute_hmac(nonce_s + nonce_c, CHALLENGE_HMAC_KEY)
    if not verify_hmac(nonce_s + nonce_c, challenge_response, CHALLENGE_HMAC_KEY):
        _send_error(sock, "Challenge response HMAC mismatch")
        raise ValueError("Client challenge response mismatch")

    # verify client signature  (non-repudiation)
    transcript_cr = nonce_s + nonce_c
    if not verify_signature(transcript_cr, sig_c, client_public_key):
        _send_error(sock, "Client signature verification failed")
        raise ValueError("Client signature verification FAILED")
    logger.info("Client signature verified ✓")

    # ── 4. ServerDone ───────────────────────────────────────────────────
    session_id = os.urandom(SESSION_ID_SIZE)
    session_key = generate_session_key()

    # Encrypt session key with client's public key
    encrypted_session_key = client_public_key.encrypt(
        session_key,
        asym_padding.OAEP(
            mgf=asym_padding.MGF1(algorithm=hashes.SHA256()),
            algorithm=hashes.SHA256(),
            label=None,
        ),
    )

    sd_payload = _encode_hs({
        "session_id": session_id.hex(),
        "encrypted_session_key": encrypted_session_key.hex(),
    })
    send_frame(sock, MessageType.HANDSHAKE_SERVER_DONE, _NULL_SID, sd_payload)

    enc_key, mac_key = derive_keys(session_key, salt=session_id)
    logger.info("Handshake complete — session %s", session_id.hex()[:12])
    return session_id, enc_key, mac_key


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def _send_error(sock: socket.socket, message: str) -> None:
    """Send an ERROR frame to the peer."""
    try:
        send_frame(
            sock, MessageType.ERROR, _NULL_SID,
            message.encode("utf-8"),
        )
    except Exception:
        pass  # best effort
